### ISSUE TITLE
transferir playlist

### ISSUE THREAD

**Issue by leozinhocds** [trustedtomato/dzdl#1]
Hello, the playlist download I get the following error.

Fetching tracks...x.data is not iterable

for songs and albums works perfectly.

**Comment by trustedtomato** [comment]
Thanks for the bug report and sorry for the slow response!

Currently the playlist download works for playlist IDs only, as I only added it because I needed it quickly (playlist download is not even an official feature = its not in --help); which means currently you can use it by, for example, `dzdl p 840785061` for this playlist: https://www.deezer.com/hu/playlist/840785061

However, this is definitely not the consistent approach so it would be the best to change the playlist/p type into search + download (which is probably what you expected), and maybe add playlist-id/P (+album-id/A and song-id/S) for the previous playlist behavior (which I used).

If you want to help, I would happily accept a PR, but else, I will implement it when I have time! :)

**Comment by trustedtomato** [comment]
Closing this issue in favor of #8 and #9
